# Generated by Django 4.1.13 on 2023-11-22 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webpush", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webpushinformation",
            options={
                "verbose_name": "Webpush Information",
                "verbose_name_plural": "Webpush Informations",
            },
        ),
    ]
