# Generated by Django 4.1.9 on 2023-05-28 10:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moneyflow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moneyflow",
            name="incoming",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=100,
                verbose_name="Incoming Money",
            ),
        ),
        migrations.AlterField(
            model_name="moneyflow",
            name="outgoing",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=100,
                verbose_name="Outgoing Money",
            ),
        ),
    ]
