# Generated by Django 4.1.7 on 2023-04-09 08:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moneyflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moneyflow',
            unique_together={('user', 'room')},
        ),
    ]
