# Generated by Django 4.1.7 on 2023-05-18 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moneyflow', '0002_alter_moneyflow_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyFlowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created at')),
                ('lastmodified_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Last modified at')),
                ('log_message', models.TextField(max_length=5000)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastmodified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('money_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneyflow.moneyflow')),
            ],
            options={
                'verbose_name': 'Money Flow Log',
                'verbose_name_plural': 'Money Flow Logs',
                'default_related_name': 'money_flow_logs',
            },
        ),
    ]
