# Generated by Django 4.1.9 on 2023-10-02 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("moneyflow", "0002_alter_moneyflow_incoming_alter_moneyflow_outgoing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moneyflowlog",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="moneyflowlog",
            name="lastmodified_by",
        ),
        migrations.RemoveField(
            model_name="moneyflowlog",
            name="money_flow",
        ),
        migrations.DeleteModel(
            name="MoneyFlow",
        ),
        migrations.DeleteModel(
            name="MoneyFlowLog",
        ),
    ]
