version: 1

language: en-US
tone_instructions: >
  Keep feedback concise, prioritize regressions or user-impacting issues,
  and call out missing tests or migrations when they matter.

project:
  name: yamsa
  root: .
  description: >
    Aligns CodeRabbit's automation with the linters and formatting hooks already
    defined in `.pre-commit-config.yaml` so AI reviews respect the same rules.

ignore:
  paths:
    - .git
    - node_modules
    - staticfiles
    - media
    - tmp
    - docs
    - build
    - dist
    - .venv
    - venv
    - .ruff_cache
    - .mypy_cache
  globs:
    - "**/__pycache__/**"
    - "**/migrations/**"
    - "**/static/**/dist/**"
    - "**/static/**/hashed/**"
    - "**/coverage_html_report/**"

rules:
  - id: ruff-format
    type: formatting
    languages: [ python ]
    command:
      - pipenv
      - run
      - ruff
      - format
      - .
    description: >
      Mirrors the `ruff-format` pre-commit hook so CodeRabbit suggestions leave
      code formatted according to the 120-column, Python 3.12 target in
      `pyproject.toml`.

  - id: ruff-lint
    type: lint
    languages: [ python ]
    command:
      - pipenv
      - run
      - ruff
      - check
      - .
      - --fix
      - --exit-non-zero-on-fix
    description: >
      Reuses the same arguments as the `ruff` hook (`--fix`, `--exit-non-zero-on-fix`)
      so CodeRabbit reports the identical diagnostics and autofix expectations.

  - id: djlint
    type: lint
    languages: [ django-templates ]
    command:
      - pipenv
      - run
      - djlint
      - apps
      - --profile
      - django
    description: >
      Keeps Django template checks in sync with the `djlint` hooks and ensures
      HTMX/Bootstrap snippets stay formatted according to the shared profile.

reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_instructions: >
    Highlight the business impact, describe required follow-up (tests, migrations,
    etc.), and keep bullet points actionable.
  collapse_walkthrough: true
  auto_review:
    enabled: true
    drafts: false
    ignore_title_keywords:
      - WIP
      - DRAFT
    labels:
      - "!wip"
  path_filters:
    - apps/**
    - "!static/**"
    - "!staticfiles/**"
    - "!media/**"
    - "!docs/**"
    - "!tmp/**"
    - "!node_modules/**"
  path_instructions:
    - path: apps/transaction/**
      instructions: >
        Focus on settlement math, rounding, and atomicity because discrepancies
        here can cause user-facing balance issues.
    - path: apps/room/**
      instructions: >
        Check that room lifecycle logic and capacity rules follow the business
        constraints described in the product docs.
  pre_merge_checks:
    title:
      mode: warning
      requirements: >
        Follow conventional commits (type[scope]: description), keep titles ~60
        characters, and clearly state the change.
    description:
      mode: warning
    issue_assessment:
      mode: warning
  tools:
    ruff:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 120000

notes:
  - >
    `pre-commit` also enforces Conventional Commit messages and prevents commits
    directly to protected branches via `conventional-pre-commit` and
    `no-commit-to-branch`. Keep those policies in mind when accepting fixes.
  - >
    `django-upgrade --target-version 6.0 --all-files` runs at `pre-push`, so
    CodeRabbit should avoid recommending patterns that would regress that
    modernization path.
  - >
    `reviews` now mirrors our CI tooling (ruff + GitHub Checks), enforces the
    same title/description conventions, and carries path-level instructions for
    core business domains so the AI review stays focused where it matters most.
