# Generated by Django 4.1.9 on 2023-05-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="highlighted",
            field=models.BooleanField(default=False),
        ),
    ]
