# Generated by Django 4.1.9 on 2023-05-28 09:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_alter_news_options_newscomment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newscomment",
            options={
                "default_related_name": "comments",
                "ordering": ("id",),
                "verbose_name": "Comment",
                "verbose_name_plural": "Comment",
            },
        ),
    ]
