# Generated by Django 4.1.9 on 2023-10-05 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0005_alter_room_preferred_currency"),
        ("news", "0004_alter_newscomment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="room",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="news",
                to="room.room",
            ),
            preserve_default=False,
        ),
    ]
