# Generated by Django 5.0.6 on 2024-06-15 08:16

import apps.core.models.mixins.full_clean_on_save
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_news_room"),
        ("room", "0007_userconnectiontoroom_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="Created at"),
                ),
                (
                    "lastmodified_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="Last modified at"
                    ),
                ),
                (
                    "action",
                    models.SmallIntegerField(
                        choices=[(1, "Created"), (2, "Modified"), (3, "Deleted"), (99, "Else")], default=99
                    ),
                ),
                ("text", models.CharField(max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "lastmodified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_lastmodified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last modified by",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, related_name="news", to="room.room"
                    ),
                ),
            ],
            options={
                "verbose_name": "FeedItem",
                "verbose_name_plural": "FeedItems",
                "ordering": ("-id",),
            },
            bases=(apps.core.models.mixins.full_clean_on_save.FullCleanOnSaveMixin, models.Model),
        ),
        migrations.DeleteModel(
            name="News",
        ),
        migrations.DeleteModel(
            name="NewsComment",
        ),
    ]
