# Generated by Django 5.0.6 on 2024-06-13 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('globally_visible', '-id'), 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='highlighted',
            new_name='globally_visible',
        ),
    ]
