# Generated by Django 5.0.6 on 2024-06-13 17:28

from django.db import migrations


def make_any_existing_news_unglobal_and_create_new_global_news(apps, schema_editor):
    News = apps.get_model("news", "News")
    Room = apps.get_model("room", "Room")
    db_alias = schema_editor.connection.alias

    News.objects.using(db_alias).all().update(globally_visible=False)

    News.objects.create(
        globally_visible=True,
        title="yamsa",
        message="Thank you for using yamsa! ❤️\n Why don't you start by creating a new room for example?",
        room=Room.objects.first(),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_alter_news_options_and_more"),
    ]

    operations = [
        migrations.RunPython(make_any_existing_news_unglobal_and_create_new_global_news, migrations.RunPython.noop)
    ]
