# Generated by Django 5.0.6 on 2024-06-15 08:16

from django.db import migrations, models


class ActionChoices(models.IntegerChoices):
    CREATED = 1, "Created"
    MODIFIED = 2, "Modified"
    DELETED = 3, "Deleted"
    ELSE = 99, "Else"


def delete_old_feed_items(apps, schema_editor):
    FeedItem = apps.get_model("news", "FeedItem")
    db_alias = schema_editor.connection.alias

    FeedItem.objects.using(db_alias).delete()


def create_generic_feed_items(apps, schema_editor):
    FeedItem = apps.get_model("news", "FeedItem")
    ParentTransaction = apps.get_model("transaction", "ParentTransaction")
    db_alias = schema_editor.connection.alias

    for transaction in ParentTransaction.objects.all().order_by("created_at"):
        text = transaction.description[:85] + "..." if len(transaction.description) > 90 else transaction.description
        FeedItem.objects.using(db_alias).create(
            text=text,
            action=ActionChoices.CREATED,
            room=transaction.room,
            created_by=transaction.created_by,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_alter_news_options_remove_news_highlighted"),
        ("transaction", "0014_parenttransaction_further_notes"),
    ]

    operations = [
        migrations.RunPython(delete_old_feed_items, migrations.RunPython.noop),
        migrations.RunPython(create_generic_feed_items, migrations.RunPython.noop),
    ]
