# Generated by Django 5.2.8 on 2025-11-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_deeplink'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Room created'), (2, 'Transaction created'), (3, 'Transaction deleted'), (4, 'User added')], null=True),
        ),
    ]
