# Generated by Django 5.2.8 on 2025-11-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0008_news_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
