# Generated by Django 6.1 on 2026-09-15 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0008_news_type_alter_news_title"),
        ("room", "0011_userconnectiontoroom_unique_user_connection_per_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news",
                to="room.room",
            ),
        ),
    ]
