# Generated by Django 4.1.9 on 2023-05-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userconnectiontoroom",
            name="user_has_seen_this_room",
            field=models.BooleanField(default=False),
        ),
    ]
