# Generated by Django 4.1.9 on 2023-05-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0002_userconnectiontoroom_user_has_seen_this_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="preferred_currency",
            field=models.SmallIntegerField(
                choices=[(1, "Euro (€)"), (2, "Pound Sterling (£)")], default=1
            ),
        ),
    ]
