# Generated by Django 4.1.9 on 2023-05-29 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0001_initial"),
        ("room", "0004_alter_room_preferred_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="preferred_currency_new",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="rooms",
                to="currency.currency",
                default=1,
            ),
            preserve_default=False,
        ),
    ]
