# Generated by Django 4.1.9 on 2023-05-29 16:35

from django.db import migrations, models
import django.db.models.deletion


def convert_currencies(apps, schema_editor):
    print()
    OLD_EURO_CONSTANT = 1
    OLD_POUND_STERLING_CONSTANT = 2

    Room = apps.get_model("room", "Room")
    Currency = apps.get_model("currency", "Currency")

    euro_currency, _ = Currency.objects.get_or_create(name="Euro", sign="€")
    pound_currency, _ = Currency.objects.get_or_create(name="Pound Sterling", sign="£")

    for room in Room.objects.all():
        if room.preferred_currency == OLD_EURO_CONSTANT:
            room.preferred_currency_new_id = euro_currency.id

        elif room.preferred_currency == OLD_POUND_STERLING_CONSTANT:
            room.preferred_currency_new_id = pound_currency.id

        room.save()


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0002_currency_created_at_currency_created_by_and_more"),
        ("room", "0004_alter_room_preferred_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="preferred_currency_new",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="rooms",
                to="currency.currency",
                default=1,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(convert_currencies, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="room",
            name="preferred_currency",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="preferred_currency_new",
            new_name="preferred_currency",
        ),
    ]
