# Generated by Django 4.1.9 on 2023-05-29 16:35

from django.db import migrations


def convert_room_preferred_currencies(apps, schema_editor):
    OLD_EURO_CONSTANT = 1
    OLD_POUND_STERLING_CONSTANT = 2

    Room = apps.get_model("room", "Room")
    Currency = apps.get_model("currency", "Currency")

    euro_currency, _ = Currency.objects.get_or_create(name="Euro", sign="€")
    pound_currency, _ = Currency.objects.get_or_create(name="Pound Sterling", sign="£")

    for room in Room.objects.all():
        if room.preferred_currency == OLD_EURO_CONSTANT:
            room.preferred_currency_new_id = euro_currency.id

        elif room.preferred_currency == OLD_POUND_STERLING_CONSTANT:
            room.preferred_currency_new_id = pound_currency.id

        room.save()


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0005_create_new_currency_field"),
    ]

    operations = [
        migrations.RunPython(
            convert_room_preferred_currencies, migrations.RunPython.noop
        ),
    ]
