# Generated by Django 4.1.13 on 2023-12-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0005_alter_room_preferred_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(max_length=50),
        ),
    ]
