# Generated by Django 4.1.9 on 2023-05-29 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0006_migrate_old_currency_fields_to_new_currency_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="preferred_currency",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="preferred_currency_new",
            new_name="preferred_currency",
        ),
    ]
