# Generated by Django 5.0.4 on 2024-05-14 08:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0006_alter_room_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userconnectiontoroom",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="Created at"),
        ),
        migrations.AddField(
            model_name="userconnectiontoroom",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="userconnectiontoroom",
            name="lastmodified_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, verbose_name="Last modified at"
            ),
        ),
        migrations.AddField(
            model_name="userconnectiontoroom",
            name="lastmodified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_lastmodified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last modified by",
            ),
        ),
    ]
