# Generated by Django 5.2.1 on 2025-05-09 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0007_userconnectiontoroom_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="users",
            field=models.ManyToManyField(
                through="room.UserConnectionToRoom", through_fields=("room", "user"), to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
