# Generated by Django 5.2.9 on 2025-12-24 11:52

import secrets
import string

from django.db import migrations, models


SHARE_HASH_LENGTH = 8


def _generate_share_hash(existing_hashes: set[str]) -> str:
    alphabet = string.ascii_letters + string.digits
    while True:
        candidate = "".join(secrets.choice(alphabet) for _ in range(SHARE_HASH_LENGTH))
        if candidate not in existing_hashes:
            existing_hashes.add(candidate)
            return candidate


def _populate_share_hashes(apps, schema_editor):
    Room = apps.get_model("room", "Room")
    existing_hashes = set(
        Room.objects.exclude(share_hash__isnull=True).values_list("share_hash", flat=True)
    )

    for room in Room.objects.filter(share_hash__isnull=True):
        room.share_hash = _generate_share_hash(existing_hashes)
        room.save(update_fields=["share_hash"])


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_alter_room_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='share_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=16, null=True, unique=True),
        ),
        migrations.RunPython(_populate_share_hashes, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='room',
            name='share_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=16, unique=True),
        ),
    ]
