# Generated by Django 6.1 on 2026-09-05 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0010_deduplicate_user_connections"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="userconnectiontoroom",
            constraint=models.UniqueConstraint(
                fields=("user", "room"), name="unique_user_connection_per_room"
            ),
        ),
    ]
