# Generated by Django 6.1 on 2026-09-19 12:38

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_userconnectiontoroom_unique_user_connection_per_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='seal_icon',
            field=models.CharField(blank=True, choices=[('key', 'key'), ('cup-hot', 'cup-hot'), ('lamp', 'lamp'), ('door-open', 'door-open'), ('leaf', 'leaf'), ('house-heart', 'house-heart'), ('piggy-bank', 'piggy-bank'), ('palette2', 'palette2')], max_length=30),
        ),
        migrations.AddField(
            model_name='room',
            name='seal_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.core.utils.determine_upload_to),
        ),
    ]
