# Generated by Django 4.1.5 on 2023-03-12 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ("-id",),
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transaction",
            },
        ),
    ]
