# Generated by Django 4.1.9 on 2023-05-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0002_transaction_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="currency",
            field=models.SmallIntegerField(
                choices=[(1, "€ - Euro"), (2, "£ - Pound Sterling")], default=1
            ),
        ),
    ]
