# Generated by Django 4.1.5 on 2023-03-12 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transaction", "0002_alter_transaction_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="paid_for",
        ),
        migrations.CreateModel(
            name="UserConnectionToTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transaction.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owes_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User-Connection to Transaction",
                "verbose_name_plural": "User-Connections to Transactions",
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="paid_for",
            field=models.ManyToManyField(
                through="transaction.UserConnectionToTransaction",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
