# Generated by Django 4.1.9 on 2023-10-03 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("debt", "0003_newdebt"),
        ("transaction", "0004_alter_transaction_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="settled",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="settled_at",
        ),
        migrations.AddField(
            model_name="transaction",
            name="new_paid_for",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="paid_for",
            field=models.ManyToManyField(
                related_name="debitors",
                through="debt.Debt",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
