# Generated by Django 4.1.7 on 2023-05-21 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0005_rename_userconnectiontotransaction_debt"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="debt",
            options={"verbose_name": "Debt", "verbose_name_plural": "Debts"},
        ),
    ]
