# Generated by Django 4.1.7 on 2023-05-21 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("debt", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transaction", "0006_alter_debt_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="paid_for",
            field=models.ManyToManyField(
                through="debt.Debt", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Debt",
        ),
    ]
