# Generated by Django 4.1.9 on 2023-10-14 05:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0008_remove_transaction_paid_for"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="new_paid_for",
            new_name="paid_for",
        ),
    ]
