# Generated by Django 4.1.9 on 2023-10-14 07:50

from django.conf import settings
from django.db import migrations


def translate_transaction_to_parent_and_child_transactions(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Transaction = apps.get_model("transaction", "Transaction")
    ParentTransaction = apps.get_model("transaction", "ParentTransaction")
    ChildTransaction = apps.get_model("transaction", "ChildTransaction")

    for transaction in Transaction.objects.using(db_alias).order_by("id"):
        parent_transaction = ParentTransaction.objects.using(db_alias).create(
            description=transaction.description,
            paid_by=transaction.paid_by,
            room=transaction.room,
            currency=transaction.currency,
            created_by=transaction.created_by,
            created_at=transaction.created_at,
            lastmodified_by=transaction.lastmodified_by,
            lastmodified_at=transaction.lastmodified_at,
        )

        for debitor in transaction.paid_for.all():
            ChildTransaction.objects.using(db_alias).create(
                parent_transaction=parent_transaction,
                paid_for=debitor,
                value=transaction.value,
                created_by=transaction.created_by,
                created_at=transaction.created_at,
                lastmodified_by=transaction.lastmodified_by,
                lastmodified_at=transaction.lastmodified_at,
            )


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transaction", "0010_parenttransaction_childtransaction"),
    ]

    operations = [
        migrations.RunPython(translate_transaction_to_parent_and_child_transactions, migrations.RunPython.noop),
    ]
