# Generated by Django 4.1.9 on 2023-10-14 10:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0011_translate_transactions_to_parents_and_children"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="childtransaction",
            options={
                "default_related_name": "child_transactions",
                "ordering": ("-id",),
                "verbose_name": "Child Transaction",
                "verbose_name_plural": "Child Transactions",
            },
        ),
    ]
