# Generated by Django 4.1.9 on 2023-10-14 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0012_alter_childtransaction_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
