# Generated by Django 4.1.13 on 2023-12-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0013_delete_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parenttransaction",
            name="description",
            field=models.TextField(max_length=50),
        ),
        migrations.AddField(
            model_name="parenttransaction",
            name="further_notes",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
