# Generated by Django 5.0.7 on 2025-03-08 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0014_parenttransaction_further_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="parenttransaction",
            name="paid_at",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="Paid at"),
        ),
    ]
