# Generated by Django 5.2.6 on 2025-11-15 23:08

import apps.core.models.mixins.full_clean_on_save
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

DEFAULT_CATEGORY_SLUG = "misc"

DEFAULT_CATEGORIES = [
    {"slug": "accommodation", "name": "Accommodation", "emoji": "🏠", "color": "#6C5CE7", "order_index": 0},
    {"slug": "groceries", "name": "Groceries", "emoji": "🛒", "color": "#00B894", "order_index": 1},
    {"slug": "restaurants-and-bars", "name": "Restaurants & Bars", "emoji": "🍽️", "color": "#FF6B6B", "order_index": 2},
    {"slug": "transport", "name": "Transport", "emoji": "🚌", "color": "#0D6EFD", "order_index": 3},
    {"slug": "activities", "name": "Activities", "emoji": "🎟️", "color": "#FFB347", "order_index": 4},
    {"slug": "household", "name": "Household", "emoji": "🧹", "color": "#6C757D", "order_index": 5},
    {"slug": "shopping", "name": "Shopping", "emoji": "🛍️", "color": "#D63384", "order_index": 6},
    {"slug": "health", "name": "Health", "emoji": "💊", "color": "#0DCB84", "order_index": 7},
    {"slug": "celebrations", "name": "Celebrations", "emoji": "🎉", "color": "#F2C94C", "order_index": 8},
    {"slug": DEFAULT_CATEGORY_SLUG, "name": "Miscellaneous", "emoji": "🌀", "color": "#ADB5BD", "order_index": 9},
]


def seed_default_categories(apps, schema_editor):
    Category = apps.get_model("transaction", "Category")

    for category_data in DEFAULT_CATEGORIES:
        Category.objects.update_or_create(
            slug=category_data["slug"],
            defaults={
                "name": category_data["name"],
                "emoji": category_data["emoji"],
                "color": category_data["color"],
                "order_index": category_data["order_index"],
                "is_default": True,
            },
        )


class Migration(migrations.Migration):
    initial = False

    dependencies = [
        ("transaction", "0015_parenttransaction_paid_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created at",
                    ),
                ),
                (
                    "lastmodified_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Last modified at",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("emoji", models.CharField(max_length=10)),
                ("color", models.CharField(blank=True, max_length=7, null=True)),
                ("order_index", models.PositiveIntegerField(default=0)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "lastmodified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_lastmodified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last modified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Category",
                "verbose_name_plural": "Transaction Categories",
                "ordering": ("order_index", "id"),
            },
            bases=(
                apps.core.models.mixins.full_clean_on_save.FullCleanOnSaveMixin,
                models.Model,
            ),
        ),
        migrations.RunPython(seed_default_categories, reverse_code=migrations.RunPython.noop),
    ]
