# Generated by Django 5.2.6 on 2025-11-15 23:08

import django.db.models.deletion
from django.db import migrations, models

DEFAULT_CATEGORY_SLUG = "misc"
# This relies on the seeded categories containing exactly ten rows with "misc" inserted last.
DEFAULT_CATEGORY_PK = 10


def backfill_parent_transactions(apps, schema_editor):
    Category = apps.get_model("transaction", "Category")
    ParentTransaction = apps.get_model("transaction", "ParentTransaction")

    default_category = Category.objects.filter(slug=DEFAULT_CATEGORY_SLUG).first()
    if not default_category:
        return

    ParentTransaction.objects.filter(category__isnull=True).update(category_id=default_category.pk)


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0016_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="parenttransaction",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="transaction.category",
            ),
        ),
        migrations.RunPython(backfill_parent_transactions, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="parenttransaction",
            name="category",
            field=models.ForeignKey(
                default=DEFAULT_CATEGORY_PK,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="transaction.category",
            ),
        ),
    ]
