# Generated by Django 5.2.8 on 2025-12-23 18:22

import apps.core.models.mixins.full_clean_on_save
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_alter_room_users'),
        ('transaction', '0018_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created at')),
                ('lastmodified_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Last modified at')),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_category_map', to='transaction.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastmodified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_categories', to='room.room')),
            ],
            options={
                'ordering': ('order_index', 'id'),
                'constraints': [models.UniqueConstraint(fields=('room', 'category'), name='unique_room_category')],
            },
            bases=(apps.core.models.mixins.full_clean_on_save.FullCleanOnSaveMixin, models.Model),
        ),
    ]
