# Generated by Django 5.2.9 on 2026-03-13 10:25

import apps.transaction.models.constants
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_currency_code'),
        ('transaction', '0019_roomcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='parenttransaction',
            name='category',
            field=models.ForeignKey(default=apps.transaction.models.constants.resolve_default_category_pk, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transaction.category'),
        ),
        migrations.AlterField(
            model_name='parenttransaction',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_transactions', to='currency.currency'),
        ),
    ]
