# Generated by Django 6.1 on 2026-09-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0020_alter_category_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parenttransaction",
            name="client_request_id",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
