# Generated by Django 4.1.9 on 2023-05-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="paypal_me_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
