# Generated by Django 4.1.9 on 2023-11-20 12:36

from django.db import migrations, models


def migrate_paypal_me_links_to_paypal_me_usernames(apps, schema_editor):
    """Forward method"""
    User = apps.get_model("account", "User")
    db_alias = schema_editor.connection.alias

    for user in User.objects.using(db_alias).all():
        if not user.paypal_me_link:
            continue

        user.paypal_me_username = user.paypal_me_link.split("/")[-1]
        user.save()


def migrate_paypal_me_usernames_to_paypal_me_links(apps, schema_editor):
    """Backward method"""
    User = apps.get_model("account", "User")
    db_alias = schema_editor.connection.alias

    for user in User.objects.using(db_alias).all():
        if not user.paypal_me_username:
            continue

        user.paypal_me_link = f"http://paypal.me/{user.paypal_me_username}"
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_user_paypal_me_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="paypal_me_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(
            migrate_paypal_me_links_to_paypal_me_usernames, migrate_paypal_me_usernames_to_paypal_me_links
        ),
        migrations.RemoveField(
            model_name="user",
            name="paypal_me_link",
        ),
    ]
