# Generated by Django 4.1.13 on 2023-11-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_remove_user_paypal_me_link_user_paypal_me_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wants_to_receive_webpush_notifications",
            field=models.BooleanField(default=True),
        ),
    ]
