# Generated by Django 4.1.13 on 2023-12-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_user_wants_to_receive_webpush_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="invitation_email_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="invitation_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
