# Generated by Django 4.1.13 on 2024-01-03 11:58

from django.db import migrations, models


def set_wants_to_receive_webpush_notifications_to_true(apps, schema_editor):
    set_wants_to_receive_webpush_notifications_to_bool(apps, schema_editor, True)


def set_wants_to_receive_webpush_notifications_to_false(apps, schema_editor):
    set_wants_to_receive_webpush_notifications_to_bool(apps, schema_editor, False)


def set_wants_to_receive_webpush_notifications_to_bool(apps, schema_editor, boolean_value: bool):
    User = apps.get_model("account", "User")
    db_alias = schema_editor.connection.alias

    User.objects.using(db_alias).update(wants_to_receive_webpush_notifications=boolean_value)


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_user_invitation_email_sent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="wants_to_receive_webpush_notifications",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            set_wants_to_receive_webpush_notifications_to_false, set_wants_to_receive_webpush_notifications_to_true
        ),
    ]
