# Generated by Django 5.0.2 on 2024-04-21 14:14

import apps.account.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_alter_user_wants_to_receive_webpush_notifications"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.account.managers.UserManager()),
            ],
        ),
    ]
