# Generated by Django 5.2.8 on 2025-11-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0013_user_wants_to_receive_payment_reminders_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(blank=True, choices=[("en", "English"), ("de", "German")], max_length=5, null=True),
        ),
    ]
