# Generated by Django 5.2.9 on 2026-03-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_user_language'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userfriendship',
            constraint=models.CheckConstraint(condition=models.Q(('user_id', models.F('friend_id')), _negated=True), name='user_cannot_friend_self'),
        ),
    ]
