# Generated by Django 6.1 on 2026-09-02 14:24

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_userfriendship_user_cannot_friend_self'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.core.utils.determine_upload_to),
        ),
    ]
