# Generated by Django 4.1.7 on 2023-05-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Debt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("settled", models.BooleanField(default=False)),
                ("settled_at", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Debt",
                "verbose_name_plural": "Debts",
            },
        ),
    ]
