# Generated by Django 4.1.7 on 2023-05-23 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("transaction", "0001_initial"),
        ("debt", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="debt",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="transaction.transaction",
            ),
        ),
        migrations.AddField(
            model_name="debt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owes_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
