# Generated by Django 4.1.9 on 2023-09-22 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("currency", "0001_initial"),
        ("room", "0005_alter_room_preferred_currency"),
        ("debt", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewDebt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("settled", models.BooleanField(default=False)),
                ("settled_at", models.DateField(blank=True, null=True)),
                (
                    "creditor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debts_to_be_settled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="debts",
                        to="currency.currency",
                    ),
                ),
                (
                    "debitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debts",
                        to="room.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "New Debt",
                "verbose_name_plural": "New Debts",
            },
        ),
    ]
