# Generated by Django 4.1.9 on 2023-10-14 06:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("debt", "0005_trigger_debt_calculation_for_all_rooms"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Debt",
        ),
    ]
