# Generated by Django 4.1.9 on 2023-10-14 06:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0005_alter_room_preferred_currency"),
        ("currency", "0002_currency_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("debt", "0006_delete_debt"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NewDebt",
            new_name="Debt",
        ),
        migrations.AlterModelOptions(
            name="debt",
            options={"verbose_name": "Debt", "verbose_name_plural": "Debts"},
        ),
    ]
