# Generated by Django 5.2.8 on 2025-11-16 21:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("debt", "0009_debt_created_at_debt_created_by_debt_lastmodified_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReminderLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="Created at"),
                ),
                (
                    "lastmodified_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="Last modified at"
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("inactive_debt", "Inactive debt reminder"),
                            ("inactive_room", "Inactive room reminder"),
                        ],
                        default="inactive_debt",
                        max_length=50,
                    ),
                ),
                ("recipients", models.JSONField(default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "lastmodified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_lastmodified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last modified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reminder log",
                "verbose_name_plural": "Reminder logs",
            },
        ),
    ]
