# Generated by Django 5.2.6 on 2025-11-16 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("debt", "0010_payment_reminder_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentreminderlog",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="paymentreminderlog",
            name="lastmodified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_lastmodified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last modified by",
            ),
        ),
        migrations.AlterField(
            model_name="paymentreminderlog",
            name="reminder_type",
            field=models.CharField(
                choices=[("inactive_debt", "Inactive debt reminder"), ("inactive_room", "Inactive room reminder")],
                default="inactive_debt",
                max_length=50,
            ),
        ),
    ]
